illich/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
]

main/urls.py
from django.contrib import admin
from django.urls import path

from main import views

admin.site.site_header = "illich administration"

urlpatterns = [
    path("", views.BlogList.as_view(), name="index"),
    path("new/", views.BlogCreate.as_view(), name="blog_create"),
    path("metadata/", views.metadata, name="metadata"),
    path("random/", views.go_random, name="go_random"),
]

main/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=500)
    url = models.URLField(unique=True)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.url

main/views.py
import random
import urllib.error
import urllib.request

from django import forms
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST
from django.views.generic import ListView
from django.views.generic.edit import CreateView

from main import models


class BlogList(ListView):
    template_name = "main/index.html"

    def get_queryset(self):
        class KeywordForm(forms.Form):
            key = forms.CharField(max_length=50)

        form = KeywordForm(self.request.GET)
        if form.is_valid():
            return models.Blog.objects.filter(
                description__icontains=form.cleaned_data["key"]
            ).order_by("?")
        else:
            return models.Blog.objects.all().order_by("?")


class BlogCreate(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = models.Blog
    fields = ["title", "url", "description"]
    success_url = reverse_lazy("index")
    success_message = "addition of %(url)s successful"

    def form_valid(self, form):
        form.cleaned_data["title"] = form.cleaned_data["title"].strip()
        form.cleaned_data["url"] = form.cleaned_data["url"].strip()
        form.cleaned_data["description"] = form.cleaned_data["description"].strip()
        return super().form_valid(form)


@require_POST
def metadata(request):
    class MetadataForm(forms.Form):
        url = forms.URLField()

    form = MetadataForm(request.POST)
    if form.is_valid():
        try:
            webpage = urllib.request.urlopen(form.cleaned_data.get("url")).read()
            webpage = str(webpage).replace("\n", " ")

            if "<title>" not in webpage:
                return HttpResponse("no title")

            title = webpage.split("<title>")[1].split("</title>")[0]
        except (urllib.error.HTTPError, urllib.error.URLError):
            title = ""
        return HttpResponse(title)
    else:
        return HttpResponse("invalid")


def go_random(request):
    all_blogs = models.Blog.objects.all()
    random_blog = random.choice(all_blogs)
    return redirect(random_blog.url)

main/templates/main/blog_form.html
{% extends 'main/layout.html' %}

{% block title %}Add blog{% endblock %}

{% block content %}
<main>
    <h1>Add blog</h1>

    <strong>Philosophy</strong>
    <blockquote cite="http://tttthis.com/blog/if-i-could-bring-one-thing-back-to-the-internet-it-would-be-blogs">
        <p>
            Nowadays when everyone is on lockdown and there are days with nothing but spaces of time to pass, nights too,
            and you can make a hot tea or a coffee and sit down but when you look there's nothing to read. You can't access
            those unique voices writing about the things they care about, that are happening to them.
        </p>
        <footer>
            — <a href="http://tttthis.com/blog/if-i-could-bring-one-thing-back-to-the-internet-it-would-be-blogs">TTTThis</a>
        </footer>
    </blockquote>

    <strong>Requirements</strong>
    <ol>
        <li>Person's, not company's</li>
        <li>Not platform-ish, like <a href="https://css-tricks.com/">css-tricks.com</a></li>
        <li>Doesn't need to be active, or have a lot of posts</li>
    </ol>

    <form method="post">
        {{ form.non_field_errors }}
        <label for="id_url">URL</label>
        {% if form.url.errors %}
            {% for error in form.url.errors %}
                <div class="form-error">{{ error|escape }}</div>
            {% endfor %}
        {% endif %}
        <input type="url" name="url" id="id_url" maxlength="500" required autofocus value="{{ form.url.value|default_if_none:"" }}">

        <label for="id_title">Title</label>
        {% if form.title.errors %}
            {% for error in form.title.errors %}
                <div class="form-error">{{ error|escape }}</div>
            {% endfor %}
        {% endif %}
        <input type="text" name="title" id="id_title" maxlength="500" required value="{{ form.title.value|default_if_none:"" }}">

        <label for="description">Small description / comment</label>
        {% if form.description.errors %}
            {% for error in form.description.errors %}
                <div class="form-error">{{ error|escape }}</div>
            {% endfor %}
        {% endif %}
        <textarea name="description" id="description" cols="30" rows="3">{{ form.description.value|default_if_none:"" }}</textarea>

        {% csrf_token %}
        <input type="submit" value="add">
    </form>

    <nav>
        <a href="{% url 'index' %}">← back to the list</a>
    </nav>
</main>
{% endblock %}

{% block scripts %}
<script>
    var csrfToken = '{{ csrf_token }}';

    function handleResponse(evt) {
        if (evt.target.status === 200) {
            document.getElementById('id_title').value = this.responseText;
        }
    }

    function requestBlogTitle() {
        // build form data
        var data = new FormData();
        var blogURL = document.getElementById('id_url').value;
        data.append('url', blogURL);

        // xhr request
        var req = new XMLHttpRequest();
        req.addEventListener('load', handleResponse);
        req.open('POST', '/metadata/');
        req.setRequestHeader('X-CSRFToken', csrfToken);
        req.send(data);
    }

    document.getElementById('id_title').addEventListener('focus', requestBlogTitle);
</script>
{% endblock %}

main/templates/main/index.html
{% extends 'main/layout.html' %}

{% block title %}Mataroa Collection{% endblock %}

{% block content %}
<main>
    <h1>Mataroa Collection</h1>
    <p>
        Curated list of personal blogs on any topic, by <a href="https://mataroa.blog/">mataroa.blog</a>.
    </p>
    <p>
        <a href="{% url 'go_random' %}">Go to a random blog</a>
    </p>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>URL</th>
                <th>Description</th>
                {% if request.user.is_authenticated %}
                <th>Admin</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for blog in object_list %}
            <tr>
                <td>{{ blog.title }}</td>
                <td><a href="{{ blog.url }}">{{ blog.url }}</a></td>
                <td>{{ blog.description }}</td>
                {% if request.user.is_authenticated %}
                <td><a href="{% url 'admin:main_blog_change' blog.id %}">Edit</a></td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</main>
<footer>
    To submit or remove your blog from this list please email
    <a href="mailto:admin+collection@mataroa.blog">admin+collection@mataroa.blog</a>.
</footer>
{% endblock %}

{% block scripts %}
<script>
    window.addEventListener('keypress', function (evt) {
        if (evt.key === 'n') {
            document.location.assign('/new');
        }
    });
</script>
{% endblock %}

main/templates/main/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>{% block title %}{% endblock %}</title>

        <link rel="stylesheet" href="{% static 'style.css' %}">
        <link rel="icon" type="image/png" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEwSURBVHgB7ZVBTsMwEEX/2GolQEjkBrkBPQI5ATlKd12SLrtr78EinACOkBuQG7QSEiClzuBpWYFUTxxY1W8ZfWe+7fEfIJFInDuEgbwtyjsQlUTm3q/Oj1+58b9qOueW2apuMQC1ge28vJlcmQcwzU8KmdfdR7/M1vUOf2XgUPzSPHv5DCq46d77QmPCQMFh5+riAs0mF7JGoQwJtosyn1j7igjYUXG9enw5pQmegDW2QizkypAkaMAYvkUkZPxLGWvAd/2Au/9FHhKomvA/0RhoEQtLQI00wOifEAvReANwtkYkEs0hTdCAvGMGNhgI99ho5oKqCfdTVx0Hjrp8s/+UNWFUBrKq3nXTvtCchOxcOweEweNYolnS0ZAE1HdGMFpm36xs61D0JhKJxE++AMI7Z3YRUW4wAAAAAElFTkSuQmCC">
    </head>
    <body>

        {% if messages %}
        <aside>
            {% for message in messages %}
            <div{% if message.tags %} class="alert-{{ message.tags }}"{% endif %}>{{ message|safe }}</div>
            {% endfor %}
        </aside>
        {% endif %}

        {% block content %}
        {% endblock %}

        {% block scripts %}
        {% endblock %}
    </body>
</html>